version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
